package com.res.provider;

import android.hardware.lights.Light;
import android.view.animation.Animation;

import com.appsflyer.internal.model.event.Launch;
import com.commsource.beautyplus.R;
import com.google.android.material.resources.TextAppearance;

public class ResSTYLE {
    public static final int ActionBar_Circle = R.style.ActionBar_Circle;
    public static final int ActionBar_Left = R.style.ActionBar_Left;
    public static final int ActionBar_Right = R.style.ActionBar_Right;
    public static final int Base_Start_Up_Theme = R.style.Base_Start_Up_Theme;
    public static final int Beautify = R.style.Beautify;
    public static final int Bg_Btn_MainColor_Ripple = R.style.Bg_Btn_MainColor_Ripple;
    public static final int BlackTheme = R.style.BlackTheme;
    public static final int CameraAnimationActivity = R.style.CameraAnimationActivity;
    public static final int CardView = R.style.CardView;
    public static final int DialogTheme = R.style.DialogTheme;
    public static final int FullScreenDialogStyle = R.style.FullScreenDialogStyle;
    public static final int IPStoreCommonTheme = R.style.IPStoreCommonTheme;
    public static final int IP_Store_Dialog = R.style.IP_Store_Dialog;
    public static final int LeftRightAnimationActivity = R.style.LeftRightAnimationActivity;
    public static final int MD_Theme = R.style.MD_Theme;
    public static final int MT_Theme_White = R.style.MT_Theme_White;
    public static final int Media2_Widget_BottomBarButton = R.style.Media2_Widget_BottomBarButton;
    public static final int Media2_Widget_EmbeddedTransportControlsButton = R.style.Media2_Widget_EmbeddedTransportControlsButton;
    public static final int Media2_Widget_FullTransportControlsButton = R.style.Media2_Widget_FullTransportControlsButton;
    public static final int Media2_Widget_MinimalTransportControlsButton = R.style.Media2_Widget_MinimalTransportControlsButton;
    public static final int Media2_Widget_TimeText = R.style.Media2_Widget_TimeText;
    public static final int Media2_Widget_TitleBar = R.style.Media2_Widget_TitleBar;
    public static final int Media2_Widget_TitleBarButton = R.style.Media2_Widget_TitleBarButton;
    public static final int MessengerButton = R.style.MessengerButton;
    public static final int MessengerButtonText = R.style.MessengerButtonText;
    public static final int MoPubFullscreenTheme = R.style.MoPubFullscreenTheme;
    public static final int NoTitleTranslucentTheme = R.style.NoTitleTranslucentTheme;
    public static final int OperateAdDialog = R.style.OperateAdDialog;
    public static final int PopwindowAnimStyle = R.style.PopwindowAnimStyle;
    public static final int PopwindowAnimTheme = R.style.PopwindowAnimTheme;
    public static final int TextEditPageDialog = R.style.TextEditPageDialog;
    public static final int Theme_BeautyActivity = R.style.Theme_BeautyActivity;
    public static final int Theme_White = R.style.Theme_White;
    public static final int Theme_transparent = R.style.Theme_transparent;
    public static final int advertDialog = R.style.advertDialog;
    public static final int advertDialogAnimation = R.style.advertDialogAnimation;
    public static final int advertPopWindow = R.style.advertPopWindow;
    public static final int alpha_in_animation = R.style.alpha_in_animation;
    public static final int animation_translate = R.style.animation_translate;
    public static final int app_wall_common_rating_style_small = R.style.app_wall_common_rating_style_small;
    public static final int arDialog = R.style.arDialog;
    public static final int ar_text_style = R.style.ar_text_style;
    public static final int baseDialog = R.style.baseDialog;
    public static final int center_zoom_in_animation = R.style.center_zoom_in_animation;
    public static final int com_facebook_activity_theme = R.style.com_facebook_activity_theme;
    public static final int com_facebook_auth_dialog = R.style.com_facebook_auth_dialog;
    public static final int com_facebook_auth_dialog_instructions_textview = R.style.com_facebook_auth_dialog_instructions_textview;
    public static final int com_facebook_button = R.style.com_facebook_button;
    public static final int com_facebook_button_like = R.style.com_facebook_button_like;
    public static final int com_facebook_button_send = R.style.com_facebook_button_send;
    public static final int com_facebook_button_share = R.style.com_facebook_button_share;
    public static final int com_facebook_loginview_default_style = R.style.com_facebook_loginview_default_style;
    public static final int common_rating_style = R.style.common_rating_style;
    public static final int dscore_interest_style = R.style.dscore_interest_style;
    public static final int filter_seekbar = R.style.filter_seekbar;
    public static final int fullScreenAppCompat = R.style.fullScreenAppCompat;
    public static final int fullScreenAppCompatTranset = R.style.fullScreenAppCompatTranset;
    public static final int fullScreenDialog = R.style.fullScreenDialog;
    public static final int googleAdActivity = R.style.googleAdActivity;
    public static final int guideDialog = R.style.guideDialog;
    public static final int guideDialogAnimations = R.style.guideDialogAnimations;
    public static final int homeBannerAdFeedbackDialog = R.style.homeBannerAdFeedbackDialog;
    public static final int interstital = R.style.interstital;
    public static final int progress_dialog = R.style.progress_dialog;
    public static final int selectable_item = R.style.selectable_item;
    public static final int setting_pop_anim = R.style.setting_pop_anim;
    public static final int settings_button_style = R.style.settings_button_style;
    public static final int settingtheme = R.style.settingtheme;
    public static final int sns_progressdialog = R.style.sns_progressdialog;
    public static final int sns_theme = R.style.sns_theme;
    public static final int sns_translucent = R.style.sns_translucent;
    public static final int sns_webview = R.style.sns_webview;
    public static final int start_up_theme = R.style.start_up_theme;
    public static final int text_normal = R.style.text_normal;
    public static final int text_universal = R.style.text_universal;
    public static final int text_universal_center = R.style.text_universal_center;
    public static final int theme = R.style.theme;
    public static final int theme_no_full_screen = R.style.theme_no_full_screen;
    public static final int tooltip_bubble_text = R.style.tooltip_bubble_text;
    public static final int top_bar = R.style.top_bar;
    public static final int translucent_no_full_screen_orientation = R.style.translucent_no_full_screen_orientation;
    public static final int up_down_animation = R.style.up_down_animation;
    public static final int updateDialog = R.style.updateDialog;
    public static final int video_load_more_btn_style_incentive = R.style.video_load_more_btn_style_incentive;
    public static final int waitingDialog = R.style.waitingDialog;
}